Controllers/TbClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LocalizaCS.Data;
using LocalizaCS.Models;

namespace LocalizaCS.Controllers
{
    public class TbClientesController : Controller
    {
        private readonly LocalizaCSContext _context;

        public TbClientesController(LocalizaCSContext context)
        {
            _context = context;
        }

        // GET: TbClientes
        public async Task<IActionResult> Index()
        {
            return View(await _context.TbClientes.ToListAsync());
        }

        // GET: TbClientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbClientes = await _context.TbClientes
                .FirstOrDefaultAsync(m => m.Id == id);
            tbClientes.Cpf = Convert.ToUInt64(tbClientes.Cpf).ToString(@"000\.000\.000\-00");
            tbClientes.Cep = Convert.ToUInt64(tbClientes.Cep).ToString(@"00000\-000");

            if (tbClientes == null)
            {
                return NotFound();
            }

            return View(tbClientes);
        }

        // GET: TbClientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TbClientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Cpf,Aniversario,Cep,Logradouro,Nro,Complemento,Bairro,Cidade,Estado")] TbClientes tbClientes)
        {
            tbClientes.Cep = tbClientes.Cep.Replace("-", "");
            tbClientes.Cpf = tbClientes.Cpf.Replace(".", "").Replace("-", "");
            tbClientes.Nome = tbClientes.Nome.ToUpper();

            if (ModelState.IsValid)
            {
                _context.Add(tbClientes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tbClientes);
        }

        // GET: TbClientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbClientes = await _context.TbClientes.FindAsync(id);
            if (tbClientes == null)
            {
                return NotFound();
            }
            tbClientes.Nro = tbClientes.Nro.Trim();
            return View(tbClientes);
        }

        // POST: TbClientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Cpf,Aniversario,Cep,Logradouro,Nro,Complemento,Bairro,Cidade,Estado")] TbClientes tbClientes)
        {
            if (id != tbClientes.Id)
            {
                return NotFound();
            }

            tbClientes.Cep = tbClientes.Cep.Replace("-", "");
            tbClientes.Cpf = tbClientes.Cpf.Replace(".", "").Replace("-", "");
            tbClientes.Nome = tbClientes.Nome.ToUpper();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tbClientes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbClientesExists(tbClientes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tbClientes);
        }

        // GET: TbClientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbClientes = await _context.TbClientes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tbClientes == null)
            {
                return NotFound();
            }

            return View(tbClientes);
        }

        // POST: TbClientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tbClientes = await _context.TbClientes.FindAsync(id);
            _context.TbClientes.Remove(tbClientes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TbClientesExists(int id)
        {
            return _context.TbClientes.Any(e => e.Id == id);
        }

        public IActionResult TbClientesCPFExists(string cpf, int id)
        {
            if (_context.TbClientes.Any(e => e.Cpf == cpf.Replace(".","").Replace("-","") && e.Id != id))
                return Json(data: "CPF já cadastrado!");

            return Json(data: true);
        }
    }
}

Controllers/TbLocacoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LocalizaCS.Data;
using LocalizaCS.Models;
using ceTe.DynamicPDF.Conversion;

namespace LocalizaCS.Views.TbLocacao
{
    public class TbLocacoesController : Controller
    {
        private readonly LocalizaCSContext _context;

        public TbLocacoesController(LocalizaCSContext context)
        {
            _context = context;
        }

        // GET: TbLocacoes
        public async Task<IActionResult> Index()
        {
            var localizaCSContext = _context.TbLocacoes.Include(t => t.Cliente).Include(t => t.Veiculo);
            return View(await localizaCSContext.ToListAsync());
        }

        // GET: TbLocacoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbLocacoes = await _context.TbLocacoes
                .Include(t => t.Cliente)
                .Include(t => t.Veiculo)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tbLocacoes == null)
            {
                return NotFound();
            }

            return View(tbLocacoes);
        }

        // GET: TbLocacoes/Create
        public IActionResult Create()
        {
            ViewData["ClienteId"] = new SelectList(_context.Set<TbClientes>(), "Id", "Nome");
            ViewData["VeiculoId"] = new SelectList(_context.Set<TbVeiculo>(), "Id", "Placa");

            return View();
        }

        // POST: TbLocacoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ClienteId,VeiculoId,Inicio,Termino")] TbLocacoes tbLocacoes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tbLocacoes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Set<TbClientes>(), "Id", "Nome", tbLocacoes.ClienteId);
            ViewData["VeiculoId"] = new SelectList(_context.Set<TbVeiculo>(), "Id", "Placa", tbLocacoes.VeiculoId);
            return View(tbLocacoes);
        }

        // GET: TbLocacoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbLocacoes = await _context.TbLocacoes.FindAsync(id);
            if (tbLocacoes == null)
            {
                return NotFound();
            }
            ViewData["ClienteId"] = new SelectList(_context.Set<TbClientes>(), "Id", "Nome", tbLocacoes.ClienteId);
            ViewData["VeiculoId"] = new SelectList(_context.Set<TbVeiculo>(), "Id", "Placa", tbLocacoes.VeiculoId);
            return View(tbLocacoes);
        }

        // POST: TbLocacoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ClienteId,VeiculoId,Inicio,Termino")] TbLocacoes tbLocacoes)
        {
            if (id != tbLocacoes.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tbLocacoes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbLocacoesExists(tbLocacoes.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Set<TbClientes>(), "Id", "Nome", tbLocacoes.ClienteId);
            ViewData["VeiculoId"] = new SelectList(_context.Set<TbVeiculo>(), "Id", "Placa", tbLocacoes.VeiculoId);
            return View(tbLocacoes);
        }

        // GET: TbLocacoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbLocacoes = await _context.TbLocacoes
                .Include(t => t.Cliente)
                .Include(t => t.Veiculo)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tbLocacoes == null)
            {
                return NotFound();
            }

            return View(tbLocacoes);
        }

        // POST: TbLocacoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tbLocacoes = await _context.TbLocacoes.FindAsync(id);
            _context.TbLocacoes.Remove(tbLocacoes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TbLocacoesExists(int id)
        {
            return _context.TbLocacoes.Any(e => e.Id == id);
        }

        public static double CalculaHoras(DateTime Inicio, DateTime Termino)
        {
            return 125.5;
        }

        public decimal GetValorHoraVeiculo (int id)
        {
            var tbVeiculos = _context.TbVeiculo.Find(id);
            return tbVeiculos.ValorHora.Value;

        }

        public IActionResult Simulacao()
        {
            ViewData["ClienteId"] = new SelectList(_context.Set<TbClientes>(), "Id", "Nome");
            ViewData["VeiculoId"] = new SelectList(_context.Set<TbVeiculo>(), "Id", "Placa");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Simulacao([Bind("Id,ClienteId,VeiculoId,Inicio,Termino")] TbLocacoes tbLocacoes)
        {
            if (ModelState.IsValid)
            {
                return Json(data: GetValorHoraVeiculo(tbLocacoes.VeiculoId));
                //_context.Add(tbLocacoes);
                //await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Set<TbClientes>(), "Id", "Nome", tbLocacoes.ClienteId);
            ViewData["VeiculoId"] = new SelectList(_context.Set<TbVeiculo>(), "Id", "Placa", tbLocacoes.VeiculoId);
            return View(tbLocacoes);
        }
        public IActionResult Simular(int id)
        {
            ViewData["ValorHora"] = GetValorHoraVeiculo(id);

            return View();
        }

        // GET: TbLocacoes/Contrato/5
        public async Task<IActionResult> Contrato(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbLocacoes = await _context.TbLocacoes
                .Include(t => t.Cliente)
                .Include(t => t.Veiculo)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tbLocacoes == null)
            {
                return NotFound();
            }

            return View(tbLocacoes);
        }

        public static void Convert(string URL)
        {
            HtmlConversionOptions options = new HtmlConversionOptions(false);
            HtmlConverter htmlConverter = new HtmlConverter(new Uri(URL), options);
            htmlConverter.Convert("converter-output.pdf");
        }

        public async Task<IActionResult> SaveDocument(int id)
        {
            HtmlConversionOptions options = new HtmlConversionOptions(false);
            options.Title = "Contrato " + id + " - LocalizaCS";
            HtmlConverter htmlConverter = new HtmlConverter(new Uri("http://localhost:8680/TbLocacoes/Contrato/" + id), options);
            htmlConverter.Convert("C:/Users/talita.salles/source/repos/LocalizaCS/wwwroot/Contratos/Contrato_" + id + ".pdf");

            return Redirect("http://localhost:8680/Contratos/Contrato_2.pdf");
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
    
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LocalizaCS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LocalizaCS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TbOperadores" asp-action="Index">Operadores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TbClientes" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TbMarcaVeiculoes" asp-action="Index">Marcas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TbModeloVeiculoes" asp-action="Index">Modelos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TbVeiculoes" asp-action="Index">Veículos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TbLocacoes" asp-action="Index">Locações</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LocalizaCS
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-mask-plugin/src/jquery.mask.js" type="text/javascript" asp-append-version="true"></script>
    <script src="~/js/jquery.inputmask.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Login</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>